<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
    <style>
        svg{
            border:1px solid;
        }

    </style>
</head>
<body>

    <header class="header main-content">
        <?php include 'forms/toolbar.php' ?>
    </header>

    <section class="draw main-content">

        <svg>

            <?php foreach($shapes as $shape): ?>
                <?= $shape; ?>
            <?php endforeach; ?>

        </svg>
    </section>

</body>
</html>
