<form id="toolbar" action="#" method="GET">
    <div id="tools">
        <fieldset>
            <label for="posX">Abscisse </label>
            <input id="posX" name="posX" size="5">

            <label for="posY">Ordonnée</label>
            <input id="posY" name="posY" size="5">

            <label for="radius">Hauteur / Rayon(X)</label>
            <input id="radius" name="radius" size="5">

            <label for="radiusY">Largeur / Rayon(Y)</label>
            <input id="radiusY" name="radiusY" size="5">

            <label for="path">Path</label>
            <input id="path" name="path" size="100">
        </fieldset>
        <fieldset>
            <label for="bckColor">Couleur fond</label>
            <select name="bckColor" id="bckColor">
                <option value="black" selected>Black</option>
                <?php foreach($colors as $key=>$value): ?>
                    <option value="<?=$key ?>"><?=$key ?></option>
                <?php endforeach; ?>

            </select>

            <label for="bdrColor">Couleur bordure</label>
            <select name="bdrColor" id="bdrColor">
                <option value="black" selected>Black</option>
                <?php foreach($colors as $key=>$value): ?>
                    <option value="<?=$key ?>"><?=$key ?></option>
                <?php endforeach; ?>

            </select>

            <label for="radiusY">Opacité</label>
            <input id="radiusY" name="opacity" size="5">

            <div>
                <input type="radio" id="square" name="tool" value="square"
                       checked>
                <label for="square">Carré</label>
            </div>

            <div>
                <input type="radio" id="circle" name="tool" value="circle">
                <label for="circle">Cercle</label>
            </div>

            <div>
                <input type="radio" id="triangle" name="tool" value="polygon">
                <label for="triangle">Polygône</label>
            </div>

            <div>
                <input type="radio" id="path" name="tool" value="path">
                <label for="path">Path</label>
            </div>

            <div>
                <input type="radio" id="path" name="tool" value="clear">
                <label for="path">Effacer le Svg</label>
            </div>



        </fieldset>
        <fieldset>
            <legend> Polygones</legend>
            <div>
                <label for="pointX">X</label>
                <input id="pointX" name="pointX" size="5">

                <label for="pointY">Y</label>
                <input id="pointY" name="pointY" size="5">

                <button type="submit">Ajouter un point</button>

                <input id="points" type="text" value="<?php if(isset($saveCoords)):?><?= $saveCoords; ?><?php endif; ?>" name="coords" >
            </div>

        </fieldset>
        <fieldset>
            <button id="submit"  name="submit" value="submit">Valider le formulaire</button>
        </fieldset>


        </div>

</form>
